### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by jesperh1** [camper0008/infraction-tracker#1]
Meget flot dokumentation med hvordan man sætter det op :)

**Comment by camper0008** [comment]
go build og kopier .env filen hvis der er en

**Comment by camper0008** [comment]
har du skillissue(s).dk?

**Comment by jesperh1** [comment]
panic: DOMAIN environment variable not set
Den behøver vel ikke vide hvad domænet er? Den skal vel bare have et port nummer?
Har du skill issues?

**Comment by camper0008** [comment]
det er sgu vist for CORS eller noget

**Comment by camper0008** [comment]
det er for CORS, bare sæt domæne env variablen som den siger, det er ikke fordi jeg sælger din data til Alphabet(r) Google(tm)
